find_program(RENODE_TEST renode-test)

add_custom_target(
  run_robot
  COMMAND PROJECT_BASE=${PROJECT_BASE}
					APPLICATION_BINARY_DIR=${APPLICATION_BINARY_DIR}
					APPLICATION_SOURCE_DIR=${APPLICATION_SOURCE_DIR}
					BOARD=${BOARD}
					${RENODE_TEST} --show-log ${APPLICATION_SOURCE_DIR}/sample.robot
  WORKING_DIRECTORY ${APPLICATION_BINARY_DIR}
  DEPENDS ${APPLICATION_BINARY_DIR}/zephyr/${KERNEL_ELF_NAME}
  USES_TERMINAL)
